### ISSUE TITLE
Testarchitektur für das Modul Medikationplan

### ISSUE THREAD

**Issue by alexzautke** [gematik/spec-ISiK-Medikation#1]
Als Entwickler vom Titus-Testsystem möchte ich wissen, wie die Testarchitektur für das Modul Medikationsplan aussehen könnte, um zu entscheiden, welche Funktionalitäten für das Titus-System entwickelt werden müssen.

AC:

- [ ] Die möglichen Architekturen wurden skizziert.

- [ ] Die dazugehörigen Sequenzdiagramme wurden skizziert.

**Comment by f-peverali** [comment]
@alexey-tschudnowsky  noch aktuell für dich? Oder kann das weg?
FYI @alexey-tschudnowsky , @MaxMTheilig

**Comment by f-peverali** [comment]
Test-System ist aufgesetzt und Produkt und Ticket damit obsolet.
