### ISSUE TITLE
targetProfile Patient und Encounter setzen

### ISSUE THREAD

**Issue by lhitc** [gematik/spec-ISiK-Medikation#24]
Für Referenzen auf Patient und Encounter sollen die jeweiligen ISiK-Profile als einzig erlaubtes targetProfile gesetzt werden.

Hierzu muss jedoch zuerst ein Paket für ISiK Basis Stufe 2 existieren, dessen Erstellung derzeit noch nicht möglich ist.

- [x] Paket für Basis Stufe 2 existiert
- [ ] targetProfile für Patient sind überall gesetzt
- [ ] targetProfile für Encounter sind überall gesetzt

**Comment by lhitc** [comment]
Paket für Basis Stufe 2 wird wahrscheinlich vor dem Medikations-Ballot nicht erscheinen.

**Comment by patrickwladowska** [comment]
Es werden keine targetProfile seit der Stufe 2 verwendet.
